"""Add gene aliases.

Revision ID: bc4cfe032773
Revises: e812b2e381c7
Create Date: 2019-07-16 15:02:11.171984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4cfe032773'
down_revision = 'e812b2e381c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'gene_aliases',
        sa.Column('id', sa.String(length=50, collation='utf8_bin'), nullable=False),
        sa.Column('gene_id', sa.String(length=50, collation='utf8_bin'), nullable=True),
        sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gene_aliases_gene_id'), 'gene_aliases', ['gene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gene_aliases_gene_id'), table_name='gene_aliases')
    op.drop_table('gene_aliases')
    # ### end Alembic commands ###
